name: Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.1
    - uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Release    
