name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Build
      run: dotnet build --configuration Release
      
  test:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Test
      run: dotnet test --configuration Release
